#!/usr/bin/env python3
"""Generate per-consumer views of wos/closure-floors.md.

WHY. The canonical file is organized by FLOOR, with each floor carrying up to three consumer
variants. Every consumer loads the whole file unconditionally (ADR-0137 declares this) and
uses 40 to 45 per cent of it. Measured 2026-08-10: 32,124 chars loaded, 17,787 to 19,161
wasted per invocation, pushing the three closure commands to 166 to 176 per cent of the
ADR-0116 ceiling once the real load is counted.

WHAT. One view per consumer, containing the preamble, and for every floor that has a
non-empty variant for that consumer, the floor's shared body plus that consumer's variant.
A floor whose variant is `None.` for a consumer is omitted from that view: `None.` exists to
tell a human reading the canonical file that the omission is deliberate, and a generated view
has no such reader.

INVARIANT. The canonical file stays the single source of truth and is the only file edited by
hand. Views are generated, and `--check` fails on drift the same way build-agent-skills.sh
does. The property that must hold is not "the files match" but "the normative text each
consumer must apply is byte-identical to what it read before", which is what
`check_closure_view_equivalence` in structural-evals.py asserts.

SECOND INVARIANT (--check only, added 2026-09-23 after the docs drift audit, gap 4). A closure
command names its floors twice more in its own prose: a "The floors are: ..." sentence where it
loads the view, and one Definition-of-done bullet per floor. Nothing compared either with the
view, so implement-approved-slice required an "Integrity floor (inline-close)" that the canonical
file gave no inline-close variant, and the drift check stayed clean. --check now fails when the
declared list and the view disagree, or when a DoD bullet names a floor the consumer's view does
not carry.

Usage:
  build-closure-floor-views.py            # write the views
  build-closure-floor-views.py --check    # exit 1 on drift or on a command/view disagreement, write nothing
"""

import hashlib
import os
import re
import sys

CANONICAL = "wos/closure-floors.md"
CONSUMERS = ("task-close", "slice-closure", "implement-approved-slice")
BANNER = (
    "<!-- GENERATED by scripts/build-closure-floor-views.py from wos/closure-floors.md.\n"
    "     Do not edit. Edit the canonical file and re-run the generator. -->\n"
)


def preamble_of(text):
    for sec in re.split(r"(?m)^(?=## )", text):
        if sec.startswith("## ") and sec.split("\n", 1)[0][3:].strip().startswith("When to load"):
            return sec.rstrip()
    return ""


def is_empty_variant(block):
    body = block.split("\n", 1)[1] if "\n" in block else ""
    return body.strip().startswith("None.")


def render(text, consumer):
    out = [BANNER, preamble_of(text), ""]
    for sec in re.split(r"(?m)^(?=## )", text):
        if not sec.startswith("## "):
            continue
        if sec.split("\n", 1)[0][3:].strip().startswith("When to load"):
            continue
        parts = re.split(r"(?m)^(?=### )", sec)
        mine = [
            p for p in parts[1:]
            if p.split("\n", 1)[0][4:].strip().startswith(f"{consumer} variant")
        ]
        mine = [p for p in mine if not is_empty_variant(p)]
        if not mine:
            continue
        out.append(parts[0].rstrip())
        out.append("")
        out.extend(p.rstrip() for p in mine)
        out.append("")
    return "\n".join(out).rstrip() + "\n"


PLATFORM = "wos/platform-runtime-floors.md"


def floor_key(name):
    """`Commit-evidence floor (ADR-0084, ...)` and `commit-evidence (ADR-0084/0100)` -> `commit-evidence`."""
    name = re.sub(r"\s*\(.*", "", name.strip()).strip().lower()
    name = re.sub(r"\s+floor$", "", name)
    return re.sub(r"[\s-]+", "-", name)


def view_floor_keys(text, consumer):
    """The floors the consumer's generated view carries, as keys."""
    keys = set()
    for block in render(text, consumer).split("\n"):
        if block.startswith("## ") and not block[3:].startswith("When to load"):
            keys.add(floor_key(block[3:]))
    return keys


def command_disagreements(text, consumer):
    """Where commands/<consumer>.md names its floors differently from its view."""
    path = f"commands/{consumer}.md"
    if not os.path.isfile(path):
        return []
    body = open(path, encoding="utf-8").read()
    view = view_floor_keys(text, consumer)
    canonical = {floor_key(h[3:]) for h in re.findall(r"(?m)^## .+$", text)
                 if not h[3:].startswith("When to load")}
    platform = set()
    if os.path.isfile(PLATFORM):
        platform = {floor_key(h[3:]) for h in re.findall(r"(?m)^## .+$", open(PLATFORM, encoding="utf-8").read())}
    out = []
    m = re.search(r"The floors are: (.+?)\.(?:\s|$)", body)
    if m:
        items = re.split(r",\s*(?:and\s+)?|\s+and\s+", m.group(1))
        declared = {floor_key(i) for i in items if i.strip()}
        for k in sorted(declared - view):
            out.append(f"{path}: 'The floors are:' names `{k}`, which is not in wos/closure-floors.{consumer}.md")
        for k in sorted(view - declared):
            out.append(f"{path}: 'The floors are:' leaves out `{k}`, which wos/closure-floors.{consumer}.md applies")
    for n, line in enumerate(body.split("\n"), 1):
        dm = re.match(r"^- ([A-Z][\w-]*(?: [\w-]+){0,3}? (?:floor|reconcile)) \(", line)
        if not dm:
            continue
        k = floor_key(dm.group(1))
        if k in view or (k in platform and k not in canonical):
            continue
        if k in canonical:
            out.append(f"{path}:{n}: the Definition of done requires the `{k}` floor, and wos/closure-floors.md "
                       f"gives it no {consumer} variant, so the view this command loads never applies it")
        else:
            out.append(f"{path}:{n}: the Definition of done names a `{k}` floor that no floors file defines")
    return out


def main():
    check = "--check" in sys.argv
    if not os.path.isfile(CANONICAL):
        print(f"build-closure-floor-views: {CANONICAL} missing", file=sys.stderr)
        return 2

    text = open(CANONICAL, encoding="utf-8").read()
    drift = []
    for consumer in CONSUMERS:
        path = f"wos/closure-floors.{consumer}.md"
        rendered = render(text, consumer)
        current = open(path, encoding="utf-8").read() if os.path.isfile(path) else None
        if check:
            if current != rendered:
                drift.append(path)
            continue
        if current == rendered:
            print(f"  unchanged: {path} ({len(rendered)} chars)")
            continue
        with open(path, "w", encoding="utf-8") as f:
            f.write(rendered)
        print(f"  wrote:     {path} ({len(rendered)} chars)")

    if check:
        disagreements = [d for c in CONSUMERS for d in command_disagreements(text, c)]
        if drift:
            print("build-closure-floor-views: DRIFT in " + ", ".join(drift), file=sys.stderr)
            print("  run: python3 scripts/build-closure-floor-views.py", file=sys.stderr)
        if disagreements:
            print("build-closure-floor-views: a closure command names its floors differently from its view:",
                  file=sys.stderr)
            for d in disagreements:
                print(f"  {d}", file=sys.stderr)
        if drift or disagreements:
            return 1
        print("build-closure-floor-views: clean")
    return 0


if __name__ == "__main__":
    sys.exit(main())
