#!/usr/bin/env python3
"""Emit the Agent Skills frontmatter block for one canonical command file.

The open Agent Skills spec fixes `metadata` as "a map from string keys to string values"
(docs/specification.mdx, 2026-08-09). Canonical command frontmatter uses flow sequences,
booleans, integers, nested maps and sequences of maps under `metadata:`, so every generated
SKILL.md violated the spec in five different shapes. A client that implements the spec strictly
rejects the whole install, not one skill.

No external dependency, deliberately: PyYAML is not installed and this repository uses no YAML
library anywhere. The frontmatter this reads is generated by the repository itself and its shapes
are enumerated below, so a hand-rolled reader is the honest tool rather than a shortcut.

Rules, in the order they apply to a value under `metadata:`:
  1. a literal block scalar (`|`, `|-`, `>`, `>-`) is already a string by the spec and is copied
     verbatim, which preserves worker_input_schema and worker_output_schema;
  2. a flow sequence `[a, b]` becomes `"a, b"`, and `[]` becomes `""`;
  3. a block sequence of scalars becomes its items joined by ` | `;
  4. a nested map or a sequence of maps becomes compact JSON inside the quotes;
  5. anything else becomes a double-quoted scalar with `\\` and `"` escaped.

The quotes are not cosmetic. `owned_sections: ['TASK_STATE.md ## Risks to watch']` flattens to a
value carrying `##`, and unquoted that opens a YAML comment and silently truncates the value.

Usage: emit-skill-frontmatter.py <canonical-command-file>
"""

import json
import re
import sys


def quote(value):
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def scalar(raw):
    raw = raw.strip()
    if len(raw) >= 2 and raw[0] == raw[-1] and raw[0] in "\"'":
        raw = raw[1:-1]
    return raw


def flow_items(inner):
    inner = inner.strip()
    if not inner:
        return []
    return [scalar(x) for x in inner.split(",") if x.strip()]


def main(argv):
    if len(argv) != 1:
        print("usage: emit-skill-frontmatter.py <command-file>", file=sys.stderr)
        return 2
    with open(argv[0], encoding="utf-8") as fh:
        lines = fh.read().split("\n")

    if not lines or lines[0] != "---":
        print(f"{argv[0]}: no frontmatter", file=sys.stderr)
        return 2
    end = lines.index("---", 1)
    fm = lines[1:end]

    out = ["---"]
    i = 0
    in_meta = False
    while i < len(fm):
        line = fm[i]

        # description becomes a literal block scalar: colons and quotes stay literal.
        if line.startswith("description: "):
            out.append("description: |-")
            out.append("  " + line[len("description: "):])
            i += 1
            continue

        if line == "metadata:":
            in_meta = True
            out.append(line)
            i += 1
            continue

        if not in_meta or not line.startswith("  ") or re.match(r"^\S", line):
            if re.match(r"^\S", line):
                in_meta = False
            out.append(line)
            i += 1
            continue

        m = re.match(r"^(\s+)([A-Za-z0-9_.-]+):(.*)$", line)
        if not m:
            out.append(line)
            i += 1
            continue
        indent, key, rest = m.group(1), m.group(2), m.group(3)
        rest_stripped = rest.strip()

        # 1. literal block scalar: already a string, copy it and its indented body verbatim.
        if rest_stripped in ("|", "|-", ">", ">-"):
            out.append(line)
            i += 1
            while i < len(fm) and (fm[i].strip() == "" or len(fm[i]) - len(fm[i].lstrip()) > len(indent)):
                out.append(fm[i])
                i += 1
            continue

        # 2. flow sequence on the same line.
        if rest_stripped.startswith("[") and rest_stripped.endswith("]"):
            items = flow_items(rest_stripped[1:-1])
            out.append(f"{indent}{key}: " + quote(", ".join(items)))
            i += 1
            continue

        # 3 and 4. an empty value opens a block: a sequence of scalars, a sequence of maps,
        #    or a nested map. Consume the block and decide by what it holds.
        if rest_stripped == "":
            block = []
            j = i + 1
            while j < len(fm) and (fm[j].strip() == "" or len(fm[j]) - len(fm[j].lstrip()) > len(indent)):
                block.append(fm[j])
                j += 1
            seq = [b for b in block if b.strip().startswith("- ")]
            if seq and len(seq) == len([b for b in block if b.strip()]):
                items = [scalar(b.strip()[2:]) for b in seq]
                out.append(f"{indent}{key}: " + quote(" | ".join(items)))
            elif seq:
                # sequence of maps: compact JSON, lossy by design (see the ADR).
                records, cur = [], None
                for b in block:
                    if not b.strip():
                        continue
                    t = b.strip()
                    if t.startswith("- "):
                        cur = {}
                        records.append(cur)
                        t = t[2:]
                    if ":" in t and cur is not None:
                        k, _, v = t.partition(":")
                        cur[k.strip()] = scalar(v)
                out.append(f"{indent}{key}: " + quote(json.dumps(records, separators=(",", ":"))))
            else:
                nested = {}
                for b in block:
                    if not b.strip():
                        continue
                    k, _, v = b.strip().partition(":")
                    nested[k.strip()] = scalar(v)
                out.append(f"{indent}{key}: " + quote(json.dumps(nested, separators=(",", ":"))))
            i = j
            continue

        # 5. plain scalar: boolean, integer or text, all quoted.
        out.append(f"{indent}{key}: " + quote(scalar(rest)))
        i += 1

    out.append("---")
    print("\n".join(out))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
