#!/usr/bin/env python3
"""
Measure token footprint of the Fhorja components and project cache scenarios.

Approximation: 4 chars per token (within ~10% of Claude / GPT tokenizers for English markdown).
Counts in chars and words too, for triangulation.

Output: a markdown report on stdout. Re-run after structural changes to see deltas.
"""

from __future__ import annotations
import argparse
import json
import math
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CHARS_PER_TOKEN = 4.0
def _pick_task_state_sample() -> Path:
    """Return the first TASK_STATE.md found under projects/*/active/* or projects/*/archive/*,
    falling back to a sentinel path the caller's fallback logic will handle gracefully."""
    candidates = sorted(ROOT.glob("projects/*/active/*/TASK_STATE.md"))
    if not candidates:
        candidates = sorted(ROOT.glob("projects/*/archive/*/TASK_STATE.md"))
    if candidates:
        return candidates[0]
    return ROOT / "projects/_no_task_state_found/TASK_STATE.md"

TASK_STATE_SAMPLE = _pick_task_state_sample()

# Anthropic prompt cache pricing multipliers
WRITE_MULTIPLIER = 1.25      # 5-minute cache write
READ_MULTIPLIER = 0.1        # cache read
BASE_MULTIPLIER = 1.0        # uncached input
MIN_CACHEABLE_OPUS_47 = 4096 # tokens; below this cache fails silently

# --exact-tokens path (opt-in, presence-gated per ADR-0046): use the o200k_base
# tokenizer via tiktoken when it is installed; otherwise fall back to the chars/4
# approximation and warn once. Default behavior (flag off) is unchanged.
EXACT_TOKENS = False
_ENCODER = None
_EXACT_WARNED = False

def _exact_encoder():
    """Return a tiktoken o200k_base encoder when --exact-tokens is on and tiktoken
    is importable; else None (and warn once on the fallback)."""
    global _ENCODER, _EXACT_WARNED
    if not EXACT_TOKENS:
        return None
    if _ENCODER is not None:
        return _ENCODER
    try:
        import tiktoken
        _ENCODER = tiktoken.get_encoding("o200k_base")
    except Exception:
        if not _EXACT_WARNED:
            print(
                f"measure-tokens: --exact-tokens requested but tiktoken is unavailable; "
                f"falling back to chars/{CHARS_PER_TOKEN:g} approximation.",
                file=sys.stderr,
            )
            _EXACT_WARNED = True
        _ENCODER = None
    return _ENCODER

def count_tokens(text: str) -> int:
    """Token count for text: exact (o200k_base) when --exact-tokens is on and tiktoken
    is present, otherwise the chars/CHARS_PER_TOKEN approximation (default, unchanged)."""
    enc = _exact_encoder()
    if enc is not None:
        return len(enc.encode(text))
    return round(len(text) / CHARS_PER_TOKEN)

def method_note() -> str:
    """Human-readable description of the active counting method."""
    if EXACT_TOKENS and _exact_encoder() is not None:
        return "o200k_base via tiktoken (exact)"
    return f"chars / {CHARS_PER_TOKEN:g} (approximation; ~10% precision vs Claude tokenizer)"

def measure(path: Path) -> tuple[int, int, int]:
    """Return (chars, words, tokens_est)."""
    text = path.read_text(encoding="utf-8")
    chars = len(text)
    words = len(text.split())
    tokens = count_tokens(text)
    return chars, words, tokens

def fmt_int(n: int) -> str:
    return f"{n:,}".replace(",", ".")

def fmt_section(title: str) -> str:
    return f"\n## {title}\n"

def measure_group(label: str, paths: list[Path]) -> tuple[list[tuple[Path, int, int, int]], int, int, int]:
    """Measure each path; return rows + group totals."""
    rows = []
    sum_c = sum_w = sum_t = 0
    for p in paths:
        c, w, t = measure(p)
        rows.append((p, c, w, t))
        sum_c += c
        sum_w += w
        sum_t += t
    return rows, sum_c, sum_w, sum_t

def per_command_rows():
    """Return list of (command_name, path, chars, words, tokens) sorted by tokens desc."""
    cmd_paths = sorted((ROOT / "commands").glob("*.md"))
    rows = []
    for p in cmd_paths:
        c, w, t = measure(p)
        rows.append((p.stem, p, c, w, t))
    rows.sort(key=lambda r: -r[4])
    return rows


def render_per_command_markdown(rows, suggest_budget=True):
    out = []
    out.append("# Per-command token baseline")
    out.append("")
    out.append("Generated by `python3 scripts/measure-tokens.py --per-command`.")
    out.append("")
    out.append(f"Method: {method_note()}.")
    out.append("")
    out.append("Each command's file size is the **transitive cost**: shared blocks under `commands/_shared/` are inlined into the command file by `sync-shared-blocks.sh`, so reading the file yields the post-sync size. The spec bootstrap (loaded by every command's `mandatory-context-bootstrap`) is a session-shared constant amortized by prompt cache (per ADR-0006) and is NOT counted here.")
    out.append("")
    cols = "| Command | Chars | Words | ~Tokens |"
    sep = "|---|---:|---:|---:|"
    if suggest_budget:
        cols = "| Command | Chars | Words | ~Tokens | Suggested budget |"
        sep = "|---|---:|---:|---:|---:|"
    out.append(cols)
    out.append(sep)
    total_t = 0
    for name, _, c, w, t in rows:
        total_t += t
        if suggest_budget:
            budget = int(math.ceil(t * 1.2 / 100.0)) * 100
            out.append(f"| `{name}` | {fmt_int(c)} | {fmt_int(w)} | {fmt_int(t)} | {fmt_int(budget)} |")
        else:
            out.append(f"| `{name}` | {fmt_int(c)} | {fmt_int(w)} | {fmt_int(t)} |")
    if suggest_budget:
        out.append(f"| **TOTAL** ({len(rows)} commands) | | | **{fmt_int(total_t)}** | |")
    else:
        out.append(f"| **TOTAL** ({len(rows)} commands) | | | **{fmt_int(total_t)}** |")
    out.append("")
    out.append(f"- Mean: {fmt_int(round(total_t / len(rows)))} tokens/command")
    out.append(f"- Largest: `{rows[0][0]}` ({fmt_int(rows[0][4])} tokens)")
    out.append(f"- Smallest: `{rows[-1][0]}` ({fmt_int(rows[-1][4])} tokens)")
    out.append("")
    out.append("Suggested budget formula: `ceil(current * 1.2 / 100) * 100`. 20% headroom for routine edits; rounded to nearest 100 for human readability. Slice 02 (ADR-0013) seeds `metadata.token-budget:` in each command from this column.")
    return "\n".join(out)


def render_per_command_json(rows):
    payload = {
        "method": method_note(),
        "commands": [
            {
                "name": name,
                "chars": c,
                "words": w,
                "tokens_est": t,
                "suggested_budget": int(math.ceil(t * 1.2 / 100.0)) * 100,
            }
            for name, _, c, w, t in rows
        ],
        "totals": {
            "count": len(rows),
            "tokens_est": sum(r[4] for r in rows),
            "mean_tokens": round(sum(r[4] for r in rows) / len(rows)) if rows else 0,
        },
    }
    return json.dumps(payload, indent=2)


def main_per_command(args):
    rows = per_command_rows()
    if args.json:
        print(render_per_command_json(rows))
    else:
        print(render_per_command_markdown(rows, suggest_budget=not args.no_suggest))


def main():
    out = []
    out.append("# Fhorja token baseline - P0 measurement")
    out.append(f"\nMethod: {method_note()}.")
    out.append(f"Anthropic prompt cache: write {WRITE_MULTIPLIER}×, read {READ_MULTIPLIER}×, min cacheable Opus 4.7 = {fmt_int(MIN_CACHEABLE_OPUS_47)} tokens.")

    # ---- Root-level docs ----
    root_files = [
        ROOT / "WORKFLOW_OPERATING_SYSTEM.md",
        ROOT / "CLAUDE.md",
        ROOT / "README.md",
        ROOT / "WORKFLOW_DEMO.md",
        ROOT / "COMMAND_PROMPT_STUBS.md",
        ROOT / "ROADMAP.md",
        ROOT / "CONTRIBUTING.md",
        ROOT / "CHANGELOG.md",
    ]
    out.append(fmt_section("Root-level documents"))
    out.append("| File | Chars | Words | ~Tokens |")
    out.append("|---|---:|---:|---:|")
    for p in root_files:
        if p.exists():
            c, w, t = measure(p)
            out.append(f"| `{p.name}` | {fmt_int(c)} | {fmt_int(w)} | {fmt_int(t)} |")

    # ---- Commands ----
    cmd_paths = sorted((ROOT / "commands").glob("*.md"))
    rows, sum_c, sum_w, sum_t = measure_group("commands", cmd_paths)
    out.append(fmt_section(f"Commands ({len(rows)} files) - sorted by token count"))
    out.append("| File | Chars | Words | ~Tokens |")
    out.append("|---|---:|---:|---:|")
    for p, c, w, t in sorted(rows, key=lambda r: -r[3]):
        out.append(f"| `{p.name}` | {fmt_int(c)} | {fmt_int(w)} | {fmt_int(t)} |")
    out.append(f"| **TOTAL** | **{fmt_int(sum_c)}** | **{fmt_int(sum_w)}** | **{fmt_int(sum_t)}** |")
    cmd_total_tokens = sum_t
    cmd_avg = round(sum_t / len(rows)) if rows else 0
    cmd_max = max(rows, key=lambda r: r[3])
    cmd_min = min(rows, key=lambda r: r[3])
    out.append(f"\n- Mean: {fmt_int(cmd_avg)} tokens/command")
    out.append(f"- Largest: `{cmd_max[0].name}` ({fmt_int(cmd_max[3])} tokens)")
    out.append(f"- Smallest: `{cmd_min[0].name}` ({fmt_int(cmd_min[3])} tokens)")

    # ---- Shared blocks ----
    shared_paths = sorted((ROOT / "commands" / "_shared").glob("*.md"))
    s_rows, s_sum_c, s_sum_w, s_sum_t = measure_group("shared", shared_paths)
    out.append(fmt_section(f"Shared blocks ({len(s_rows)} files)"))
    out.append("| File | Chars | Words | ~Tokens |")
    out.append("|---|---:|---:|---:|")
    for p, c, w, t in s_rows:
        out.append(f"| `{p.name}` | {fmt_int(c)} | {fmt_int(w)} | {fmt_int(t)} |")
    out.append(f"| **TOTAL** | **{fmt_int(s_sum_c)}** | **{fmt_int(s_sum_w)}** | **{fmt_int(s_sum_t)}** |")
    shared_total_tokens = s_sum_t

    # ---- Templates ----
    tpl_paths = sorted((ROOT / "templates").glob("*.md"))
    t_rows, t_sum_c, t_sum_w, t_sum_t = measure_group("templates", tpl_paths)
    out.append(fmt_section(f"Templates ({len(t_rows)} files)"))
    out.append("| File | Chars | Words | ~Tokens |")
    out.append("|---|---:|---:|---:|")
    for p, c, w, t in t_rows:
        out.append(f"| `{p.name}` | {fmt_int(c)} | {fmt_int(w)} | {fmt_int(t)} |")
    out.append(f"| **TOTAL** | **{fmt_int(t_sum_c)}** | **{fmt_int(t_sum_w)}** | **{fmt_int(t_sum_t)}** |")

    # ---- TASK_STATE sample ----
    out.append(fmt_section("TASK_STATE sample (representative)"))
    if TASK_STATE_SAMPLE.exists():
        c, w, t = measure(TASK_STATE_SAMPLE)
        out.append(f"- Path: `{TASK_STATE_SAMPLE.relative_to(ROOT)}`")
        out.append(f"- Chars: {fmt_int(c)} | Words: {fmt_int(w)} | ~Tokens: {fmt_int(t)}")
        task_state_tokens = t
    else:
        out.append("Sample TASK_STATE.md not found.")
        task_state_tokens = 3000

    # ---- Spec detail ----
    wos_path = ROOT / "WORKFLOW_OPERATING_SYSTEM.md"
    wos_c, wos_w, wos_t = measure(wos_path)
    out.append(fmt_section("WORKFLOW_OPERATING_SYSTEM.md detail"))
    out.append(f"- Total: {fmt_int(wos_c)} chars / {fmt_int(wos_w)} words / **~{fmt_int(wos_t)} tokens**")

    # Approximate sizes of key sections by counting between top-level headers
    text = wos_path.read_text(encoding="utf-8")
    lines = text.split("\n")
    sections = []
    cur_title = None
    cur_chars = 0
    for line in lines:
        if line.startswith("## "):
            if cur_title:
                sections.append((cur_title, cur_chars))
            cur_title = line[3:].strip()
            cur_chars = len(line) + 1
        else:
            cur_chars += len(line) + 1
    if cur_title:
        sections.append((cur_title, cur_chars))
    sections_sorted = sorted(sections, key=lambda s: -s[1])

    out.append("\n**Top 12 spec sections by size:**\n")
    out.append("| Section | Chars | ~Tokens |")
    out.append("|---|---:|---:|")
    for title, chars in sections_sorted[:12]:
        out.append(f"| {title} | {fmt_int(chars)} | {fmt_int(round(chars/CHARS_PER_TOKEN))} |")

    # ---- Cache projection: 5-step flow ----
    out.append(fmt_section("Cache scenario projection (5-step typical flow)"))
    out.append("Flow modeled: `task-init` → `impact-analysis` → `implementation-plan` → `implement-approved-slice` → `pr-package`.")
    out.append(f"Assumption: each command loads full spec ({fmt_int(wos_t)} tokens) + its own command file + all shared blocks ({fmt_int(shared_total_tokens)} tokens) + current TASK_STATE ({fmt_int(task_state_tokens)} tokens) + ~300 tokens user input.\n")

    flow = ["task-init.md", "impact-analysis.md", "implementation-plan.md", "implement-approved-slice.md", "pr-package.md"]
    cmd_tokens = {}
    for name in flow:
        p = ROOT / "commands" / name
        if p.exists():
            _, _, t = measure(p)
            cmd_tokens[name] = t
        else:
            cmd_tokens[name] = cmd_avg
    user_input = 300

    out.append("| Step | Command | Cmd ~tok | TASK_STATE ~tok | Total static (cacheable) | Total dynamic |")
    out.append("|---|---|---:|---:|---:|---:|")
    static_per_step = wos_t + shared_total_tokens
    for i, name in enumerate(flow, 1):
        # static portion: spec + shared (same across all steps)
        # dynamic portion: command file + TASK_STATE + user input
        dynamic = cmd_tokens[name] + task_state_tokens + user_input
        out.append(f"| {i} | `{name}` | {fmt_int(cmd_tokens[name])} | {fmt_int(task_state_tokens)} | {fmt_int(static_per_step)} | {fmt_int(dynamic)} |")

    # Scenario A: current architecture, full spec, with cache (Claude Code default)
    cache_write_step1 = static_per_step * WRITE_MULTIPLIER + cmd_tokens[flow[0]] + task_state_tokens + user_input
    cache_read_steps_2_5 = sum(
        static_per_step * READ_MULTIPLIER + cmd_tokens[name] + task_state_tokens + user_input
        for name in flow[1:]
    )
    scenario_a = cache_write_step1 + cache_read_steps_2_5

    # Scenario B: no cache (e.g., new chat per command, or cache TTL exceeded)
    scenario_b = sum(
        static_per_step + cmd_tokens[name] + task_state_tokens + user_input
        for name in flow
    )

    # Scenario C: spec reduced to ~3k (P1 lazy-load), no other changes
    target_wos_core = 3000
    static_after_p1 = target_wos_core + shared_total_tokens
    scenario_c_write = static_after_p1 * WRITE_MULTIPLIER + cmd_tokens[flow[0]] + task_state_tokens + user_input
    scenario_c_read = sum(
        static_after_p1 * READ_MULTIPLIER + cmd_tokens[name] + task_state_tokens + user_input
        for name in flow[1:]
    )
    scenario_c = scenario_c_write + scenario_c_read

    # Scenario D: P1 + P2 + P3 (spec reduced + shared not inlined / referenced lazily)
    # Assume shared blocks effectively halved on average via lazy load
    static_after_p123 = target_wos_core + (shared_total_tokens // 2)
    scenario_d_write = static_after_p123 * WRITE_MULTIPLIER + cmd_tokens[flow[0]] + task_state_tokens + user_input
    scenario_d_read = sum(
        static_after_p123 * READ_MULTIPLIER + cmd_tokens[name] + task_state_tokens + user_input
        for name in flow[1:]
    )
    scenario_d = scenario_d_write + scenario_d_read

    # Scenario E: Skills format (each command's body loads only on invocation; descriptions only loaded for routing)
    # Approximation: only invoked command body loads, plus TASK_STATE, plus minimal core (3k for WOS_CORE)
    # No "all shared" cost (only blocks the invoked skill references, ~300 tokens average)
    skill_overhead_per_step = 300  # referenced shared blocks for that skill
    n_skills = len(list((ROOT / "commands").glob("*.md")))  # dynamic: matches commands/*.md count
    description_budget = 50 * n_skills  # rough: N skills x ~50 token descriptions in router
    static_after_skills = target_wos_core + description_budget
    scenario_e_write = static_after_skills * WRITE_MULTIPLIER + cmd_tokens[flow[0]] + skill_overhead_per_step + task_state_tokens + user_input
    scenario_e_read = sum(
        static_after_skills * READ_MULTIPLIER + cmd_tokens[name] + skill_overhead_per_step + task_state_tokens + user_input
        for name in flow[1:]
    )
    scenario_e = scenario_e_write + scenario_e_read

    out.append("\n### Scenario costs (token-equivalents for the full 5-step flow)\n")
    out.append("| Scenario | Description | ~Token-equivalents | vs A |")
    out.append("|---|---|---:|---:|")
    out.append(f"| **A** | Current arch, full spec, cache hit (default Claude Code) | {fmt_int(round(scenario_a))} | 1.00× |")
    out.append(f"| **B** | Current arch, full spec, no cache (new chat per command) | {fmt_int(round(scenario_b))} | {scenario_b/scenario_a:.2f}× |")
    out.append(f"| **C** | After P1 (WOS_CORE ≤3k + topics lazy), with cache | {fmt_int(round(scenario_c))} | {scenario_c/scenario_a:.2f}× |")
    out.append(f"| **D** | After P1+P2+P3 (WOS_CORE + shared deduped), with cache | {fmt_int(round(scenario_d))} | {scenario_d/scenario_a:.2f}× |")
    out.append(f"| **E** | After Agent Skills migration (lazy body load), with cache | {fmt_int(round(scenario_e))} | {scenario_e/scenario_a:.2f}× |")

    out.append("\n### Key observations\n")
    obs = []
    obs.append(f"Spec alone is **{fmt_int(wos_t)} tokens** ({wos_t/cmd_total_tokens*100:.0f}% of all commands combined).")
    obs.append(f"Shared blocks total **{fmt_int(shared_total_tokens)} tokens** but get **inlined into {n_skills} commands** by `sync-shared-blocks.sh` (actual repo footprint is ~{n_skills}x higher than the source).")
    obs.append(f"Largest spec section is **'{sections_sorted[0][0]}'** at {fmt_int(round(sections_sorted[0][1]/CHARS_PER_TOKEN))} tokens (single section bigger than several commands combined).")
    obs.append(f"Min cacheable size for Opus 4.7 is {fmt_int(MIN_CACHEABLE_OPUS_47)} tokens. Spec+shared = {fmt_int(static_per_step)} tokens, well above the threshold (cache works).")
    obs.append(f"After P1 (WOS_CORE <=3k), static portion drops to {fmt_int(static_after_p1)} tokens (still above the {fmt_int(MIN_CACHEABLE_OPUS_47)}-token cache floor, so we keep cache benefits).")
    obs.append(f"Scenario A → C delta: **{(1 - scenario_c/scenario_a)*100:.0f}% fewer token-equivalents** in a typical 5-step session.")
    obs.append(f"Scenario A -> E (full Skills migration) delta: **{(1 - scenario_e/scenario_a)*100:.0f}% fewer token-equivalents** (biggest win comes from lazy body load).")
    obs.append(f"Scenario A vs B (no cache fallback): cache currently saves **{(1 - scenario_a/scenario_b)*100:.0f}%** vs cold reads. If a user clears chat per command, they pay full price every time.")
    for o in obs:
        out.append(f"- {o}")

    print("\n".join(out))


def parse_args():
    p = argparse.ArgumentParser(description="Measure Fhorja token footprint and project cache scenarios.")
    p.add_argument("--per-command", action="store_true",
                   help="Emit per-command transitive token cost (no full spec scenario).")
    p.add_argument("--json", action="store_true",
                   help="With --per-command: emit JSON instead of markdown.")
    p.add_argument("--no-suggest", action="store_true",
                   help="With --per-command (markdown): omit the suggested budget column.")
    p.add_argument("--exact-tokens", action="store_true",
                   help="Count tokens with o200k_base via tiktoken when installed (exact); "
                        "falls back to the chars/4 approximation with a warning when it is not.")
    return p.parse_args()


if __name__ == "__main__":
    args = parse_args()
    EXACT_TOKENS = bool(getattr(args, "exact_tokens", False))
    if args.per_command:
        main_per_command(args)
    else:
        main()
